version: "3.9"
services:
  db:
    image: postgres:13.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword  
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=db
      - PGUSER=postgres
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db